/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class OntologicalModelingLanguageFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
