/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class OntologicalModelingLanguageFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(OntologicalModelingLanguageFileType.INSTANCE, AbstractOntologicalModelingLanguageFileType.DEFAULT_EXTENSION);
	}

}
