/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class OntologicalModelingLanguageLanguage extends AbstractXtextLanguage {

	public static final OntologicalModelingLanguageLanguage INSTANCE = new OntologicalModelingLanguageLanguage();

	private OntologicalModelingLanguageLanguage() {
		super("jpl.imce.oml.specification.OntologicalModelingLanguage");
	}

}
