/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.ui.tests;

import com.google.inject.Injector;
import jpl.imce.oml.specification.ui.internal.SpecificationActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class OntologicalModelingLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpecificationActivator.getInstance().getInjector("jpl.imce.oml.specification.OntologicalModelingLanguage");
	}

}
