/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.highlighting


class OntologicalModelingLanguageColorSettingsPage extends OntologicalModelingLanguageBaseColorSettingsPage {
}
