/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.highlighting;

import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class OntologicalModelingLanguageBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public OntologicalModelingLanguageBaseColorSettingsPage() {
		OntologicalModelingLanguageLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return OntologicalModelingLanguageLanguage.INSTANCE.getDisplayName();
	}
}
