/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.highlighting;

import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class OntologicalModelingLanguageSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public OntologicalModelingLanguageSemanticHighlightVisitor() {
		OntologicalModelingLanguageLanguage.INSTANCE.injectMembers(this);
	}
}
