/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;
import org.jetbrains.annotations.NotNull;

public class OntologicalModelingLanguageSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return OntologicalModelingLanguageLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
