/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.ui;

import jpl.imce.oml.specification.ui.AbstractOntologicalModelingLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OntologicalModelingLanguageUiModule extends AbstractOntologicalModelingLanguageUiModule {
  public OntologicalModelingLanguageUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
