/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class OntologicalModelingLanguageIdeaModule extends AbstractOntologicalModelingLanguageIdeaModule {
}
