/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.tests

import com.google.inject.Inject
import jpl.imce.oml.specification.ecore.TerminologyExtent
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.junit4.validation.ValidationTestHelper

@RunWith(XtextRunner)
@InjectWith(OntologicalModelingLanguageInjectorProvider)
class OMLTerminologyExtensionTest1 {

	@Inject
	ParseHelper<TerminologyExtent> parseHelper

	@Inject 
	extension ValidationTestHelper

	@Test 
	def void extensionTest() {
		
		val result = parseHelper.parse(
'''
annotationProperty rdfs:label=<http://www.w3.org/2000/01/rdf-schema#label>
annotationProperty dc:description=<http://purl.org/dc/elements/1.1/>

open terminology <http://imce.jpl.nasa.gov/foundation/base/base>
{
	
}

open terminology <http://imce.jpl.nasa.gov/foundation/mission/mission>
{	
	extends base
}
''')
		Assert.assertNotNull(result)
		result.assertNoErrors
		
		System.out.println(this.class.name + " OK!")
	}
	
}
