/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.tests

import com.google.inject.Inject
import jpl.imce.oml.specification.ecore.TerminologyExtent
import jpl.imce.oml.specification.ecore.extensions.OMLExtensions
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(OntologicalModelingLanguageInjectorProvider)
class OMLTerminologyGraph2Test{

	@Inject
	ParseHelper<TerminologyExtent> parseHelper

	@Inject 
	extension ValidationTestHelper

	@Inject
	extension OMLExtensions
	
	@Test 
	def void terminologyGraph2() {
		
		val result = parseHelper.parse(
'''
annotationProperty rdfs:label=<http://www.w3.org/2000/01/rdf-schema#label>
annotationProperty dc:description=<http://purl.org/dc/elements/1.1/>

open terminology <http://imce.jpl.nasa.gov/foundation/base/base>
{
	aspect IdentifiedElement	
}

open terminology <http://imce.jpl.nasa.gov/foundation/mission/mission>
{
	extends base
	
	concept Component
	
	Component extendsAspect base:IdentifiedElement
}
''')
		Assert.assertNotNull(result)
		result.phasedResolveAll	
		result.assertNoErrors
		
		System.out.println(this.class.name + " OK!")
	}

}
