/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class OntologicalModelingLanguageFacetType extends AbstractFacetType<OntologicalModelingLanguageFacetConfiguration> {

	public static final FacetTypeId<Facet<OntologicalModelingLanguageFacetConfiguration>> TYPEID = new FacetTypeId<Facet<OntologicalModelingLanguageFacetConfiguration>>("jpl.imce.oml.specification.OntologicalModelingLanguage");

	public OntologicalModelingLanguageFacetType() {
		super(TYPEID, "jpl.imce.oml.specification.OntologicalModelingLanguage", "OntologicalModelingLanguage");
		OntologicalModelingLanguageLanguage.INSTANCE.injectMembers(this);
	}
}
