/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang


class OntologicalModelingLanguageFileType extends AbstractOntologicalModelingLanguageFileType {
	public static final OntologicalModelingLanguageFileType INSTANCE = new OntologicalModelingLanguageFileType()
	
	new() {
		super(OntologicalModelingLanguageLanguage.INSTANCE)
	}
}
