/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageFileType;
import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class OntologicalModelingLanguageFileImpl extends BaseXtextFile {

	public OntologicalModelingLanguageFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, OntologicalModelingLanguageLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return OntologicalModelingLanguageFileType.INSTANCE;
	}
}
