/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class OntologicalModelingLanguageCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public OntologicalModelingLanguageCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(OntologicalModelingLanguageLanguage.INSTANCE, psiModificationTracker);
	}

}
