/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractOntologicalModelingLanguageCompletionContributor extends TerminalsCompletionContributor {
	public AbstractOntologicalModelingLanguageCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
