/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.completion

import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class OntologicalModelingLanguageCompletionContributor extends AbstractOntologicalModelingLanguageCompletionContributor {
	new() {
		this(OntologicalModelingLanguageLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
