/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification;

import jpl.imce.oml.specification.AbstractOntologicalModelingLanguageRuntimeModule;
import jpl.imce.oml.specification.linking.OWLLinkingService;
import jpl.imce.oml.specification.scoping.OMLImportedNamespaceAwareLocalScopeProvider;
import jpl.imce.oml.specification.util.OMLQualifiedNameConverter;
import jpl.imce.oml.specification.util.OMLQualifiedNameProvider;
import jpl.imce.oml.specification.util.OMLValueConverterService;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntologicalModelingLanguageRuntimeModule extends AbstractOntologicalModelingLanguageRuntimeModule {
  public Class<? extends ILinkingService> bindILinkingService() {
    return OWLLinkingService.class;
  }
  
  public Class<? extends IScopeProvider> bindIScopeProvider() {
    return OMLImportedNamespaceAwareLocalScopeProvider.class;
  }
  
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return OMLValueConverterService.class;
  }
  
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return OMLQualifiedNameProvider.class;
  }
  
  public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
    return OMLQualifiedNameConverter.class;
  }
}
