/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification;

import com.google.inject.Injector;
import jpl.imce.oml.specification.OntologicalModelingLanguageStandaloneSetupGenerated;
import jpl.imce.oml.specification.ecore.OMLPackage;
import org.eclipse.emf.ecore.EPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntologicalModelingLanguageStandaloneSetup extends OntologicalModelingLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    OntologicalModelingLanguageStandaloneSetup _ontologicalModelingLanguageStandaloneSetup = new OntologicalModelingLanguageStandaloneSetup();
    _ontologicalModelingLanguageStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey(OMLPackage.eNS_URI);
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put(OMLPackage.eNS_URI, OMLPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
