/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class OntologicalModelingLanguageWebModule extends AbstractOntologicalModelingLanguageWebModule {
}
