/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.highlighting;

import jpl.imce.oml.specification.idea.highlighting.OntologicalModelingLanguageBaseColorSettingsPage;

@SuppressWarnings("all")
public class OntologicalModelingLanguageColorSettingsPage extends OntologicalModelingLanguageBaseColorSettingsPage {
}
