/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea;

import com.google.inject.Injector;

@SuppressWarnings("all")
public class OntologicalModelingLanguageStandaloneSetupIdea /* implements OntologicalModelingLanguageStandaloneSetupGenerated  */{
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from OntologicalModelingLanguageRuntimeModule to Module");
  }
}
