/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea;

import com.google.inject.Injector;
import jpl.imce.oml.specification.OntologicalModelingLanguageStandaloneSetupGenerated;

@SuppressWarnings("all")
public class OntologicalModelingLanguageStandaloneSetupIdea extends OntologicalModelingLanguageStandaloneSetupGenerated {
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Modules2 is undefined"
      + "\nmixin cannot be resolved");
  }
}
