/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea;

import jpl.imce.oml.specification.idea.AbstractOntologicalModelingLanguageIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class OntologicalModelingLanguageIdeaModule extends AbstractOntologicalModelingLanguageIdeaModule {
}
