/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.ui;

import com.google.inject.Injector;
import jpl.imce.oml.specification.ui.internal.SpecificationActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OntologicalModelingLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SpecificationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SpecificationActivator.getInstance().getInjector(SpecificationActivator.JPL_IMCE_OML_SPECIFICATION_ONTOLOGICALMODELINGLANGUAGE);
	}
	
}
