/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import jpl.imce.oml.specification.OntologicalModelingLanguageRuntimeModule;
import jpl.imce.oml.specification.OntologicalModelingLanguageStandaloneSetup;
import jpl.imce.oml.specification.web.OntologicalModelingLanguageWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OntologicalModelingLanguageWebSetup extends OntologicalModelingLanguageStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final OntologicalModelingLanguageRuntimeModule runtimeModule = new OntologicalModelingLanguageRuntimeModule();
    final OntologicalModelingLanguageWebModule webModule = new OntologicalModelingLanguageWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public OntologicalModelingLanguageWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
