/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import jpl.imce.oml.specification.web.AbstractOntologicalModelingLanguageWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OntologicalModelingLanguageWebModule extends AbstractOntologicalModelingLanguageWebModule {
  public OntologicalModelingLanguageWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
