/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.ui.contentassist;

import jpl.imce.oml.specification.ui.contentassist.AbstractOntologicalModelingLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OntologicalModelingLanguageProposalProvider extends AbstractOntologicalModelingLanguageProposalProvider {
}
