/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang;

import jpl.imce.oml.specification.idea.lang.AbstractOntologicalModelingLanguageFileType;

@SuppressWarnings("all")
public class OntologicalModelingLanguageFileType extends AbstractOntologicalModelingLanguageFileType {
  public final static OntologicalModelingLanguageFileType INSTANCE = new OntologicalModelingLanguageFileType();
  
  public OntologicalModelingLanguageFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(OntologicalModelingLanguageLanguage) is undefined");
  }
}
