/**
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.completion;

import jpl.imce.oml.specification.idea.completion.AbstractOntologicalModelingLanguageCompletionContributor;

@SuppressWarnings("all")
public class OntologicalModelingLanguageCompletionContributor extends AbstractOntologicalModelingLanguageCompletionContributor {
  public OntologicalModelingLanguageCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor OntologicalModelingLanguageCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public OntologicalModelingLanguageCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
