/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOntologicalModelingLanguageScopeProvider extends DelegatingScopeProvider {
}
