/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OntologicalModelingLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("jpl/imce/oml/specification/idea/parser/antlr/internal/PsiInternalOntologicalModelingLanguage.tokens");
	}
}
