/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea.lang.pom;

import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class OntologicalModelingLanguagePomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public OntologicalModelingLanguagePomDeclarationSearcher() {
		super(OntologicalModelingLanguageLanguage.INSTANCE);
	}
}
