/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import jpl.imce.oml.specification.idea.lang.OntologicalModelingLanguageLanguage;

public class OntologicalModelingLanguageExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return OntologicalModelingLanguageLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
