/*
 * generated by Xtext 2.10.0
 */
package jpl.imce.oml.specification.scoping

/*
 * Since the OntologicalModelingLanguageRuntimeModule explicitly binds the scope provider to OMLImportedNamespaceAwareLocalScopeProvider,
 * this Xtext 2.10.0-generated class seems to be unnecessary.
 */
 
/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class OntologicalModelingLanguageScopeProvider extends AbstractOntologicalModelingLanguageScopeProvider {

	
}
